### ISSUE TITLE
Enhance Demo Security Approach

### ISSUE THREAD

**Issue by grempe** [tyvdh/stellar-demo-wallet#2]
You might look at using a more modern encryption library to protect the wallet in the demo app. You might also find a massive savings in terms of the size of the code that needs to be transpiled and downloaded to the browser when compared to the current usage of SJCL (which is old and huge). A possible suggestion:

https://github.com/dchest/tweetnacl-js

You can play with it at:

https://tweetnacl.js.org/#/

Also, you should "stretch" the pin code and not use it directly as an encryption key. Stretching turns a weak password (e.g. "1234") into 32 or more bytes of secure data. The key stretching process is also "memory and CPU hard". Meaning that it might take a few hundred ms to stretch your pin code into a good key. This prevents someone that has access to your encrypted wallet from attempting brute force attacks on the pin code by slowing down that process dramatically (while not being noticable to the user).

An example lib to look at would be:

https://antelle.net/argon2-browser/

More info about key stretching:

https://en.wikipedia.org/wiki/Key_stretching

Cheers!

**Comment by tyvdh** [comment]
Thanks so much for this!

I've implemented a fix using argon2 and tweetnacl. You can see the two main files here and here:

https://github.com/tyvdh/stellar-demo-wallet/blob/update-security/src/services/argon2.ts
https://github.com/tyvdh/stellar-demo-wallet/blob/update-security/src/services/tweetnacl.ts

I'll admit I'm a little lost on the best settings for the argon2 hash, maybe you could look that over and advise?

```json
{
  ...
  time: 100,
  mem: 1024,
  hashLen: 32,
  type: argon2.ArgonType.Argon2d
}
```

Also didn't see a very large size difference, it's just this vs this.

https://raw.githubusercontent.com/TinyAnvil/sjcl/master/sjcl.js
https://raw.githubusercontent.com/dchest/tweetnacl-js/master/nacl-fast.min.js

Probably fine to still make the switch though as nacl does seem more up-to-date.
